let gameSeq = [];  //The correct color pattern generated by the game
let userSeq = [];  //The pattern the user clicks (to be matched with gameSeq)
let btns = ["yellow", "red", "purple", "green"];
let started = false;
let level = 0;
let highScore = 0;
const highScoreDisplay = document.getElementById("high-score");
let overlay = document.getElementById("overlay");


overlay.classList.add("flash-red");
setTimeout(() => {
  overlay.classList.remove("flash-red");
}, 300);
let h2 = document.querySelector("h2");

document.addEventListener("keypress", function () {
  if (!started) {
    started = true;
    levelUp();
  }
});

function gameFlash(btn) {
  btn.classList.add("flash");
  setTimeout(() => btn.classList.remove("flash"), 200);
}

function userFlash(btn) {
  btn.classList.add("userflash");
  setTimeout(() => btn.classList.remove("userflash"), 200);
}

function levelUp() {
  userSeq = [];
  level++;
  h2.innerText = `Level ${level}`;

  let randIdx = Math.floor(Math.random() * 4);
  let randColor = btns[randIdx];
  let randBtn = document.querySelector(`.${randColor}`);
  gameSeq.push(randColor);

  gameFlash(randBtn);
}

function checkAns(idx) {
  if (userSeq[idx] === gameSeq[idx]) {
    if (userSeq.length === gameSeq.length) {
      setTimeout(levelUp, 1000);
    }
  } else {
    // Update high score if current score is higher
    if (level > highScore) {
      highScore = level;
      highScoreDisplay.innerText = `High Score: ${highScore}`;
    }

    h2.innerHTML = `Game Over! Your score was <b>${level}</b><br>Press any key to restart`;
    let overlay = document.getElementById("overlay");
    overlay.classList.add("flash-red");
    setTimeout(() => {
      overlay.classList.remove("flash-red");
    }, 300);
    reset();
  }
}


function btnPress() {
  let btn = this;
  userFlash(btn);

  let userColor = btn.getAttribute("id");
  userSeq.push(userColor);

  checkAns(userSeq.length - 1);
}

let allBtns = document.querySelectorAll(".btn");
allBtns.forEach((btn) => btn.addEventListener("click", btnPress));

function reset() {
  started = false;
  gameSeq = [];
  userSeq = [];
  level = 0;
}
